# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=30)),
                ('start_term', models.DateField()),
                ('end_term', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_id', models.CharField(max_length=30, unique=True)),
                ('effective', models.DateField()),
                ('expires', models.DateField()),
                ('checked', models.BooleanField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_id', models.CharField(max_length=30, unique=True)),
                ('grant', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('issue_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=30)),
                ('gains', models.DecimalField(decimal_places=2, max_digits=7)),
                ('losses', models.DecimalField(decimal_places=2, max_digits=7)),
                ('checked', models.BooleanField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('notes', models.TextField()),
                ('docs', models.ManyToManyField(blank=True, to='core.Doc')),
            ],
        ),
        migrations.CreateModel(
            name='Proc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('status', models.BooleanField()),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='money',
            name='proc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Proc'),
        ),
        migrations.AddField(
            model_name='hat',
            name='proc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Proc'),
        ),
        migrations.AddField(
            model_name='doc',
            name='proc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Proc'),
        ),
        migrations.AddField(
            model_name='bread',
            name='proc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Proc'),
        ),
    ]
