# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='money',
            options={'verbose_name_plural': 'money'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
        migrations.AlterField(
            model_name='bread',
            name='proc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Proc'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='hat',
            name='proc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Proc'),
        ),
        migrations.AlterField(
            model_name='money',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='proc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Proc'),
        ),
        migrations.AlterField(
            model_name='proc',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proc',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='proc',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
