# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161016_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='proc',
            name='long_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
