# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_proc_long_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proc',
            name='long_id',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
