# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161018_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='proc',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Person'),
        ),
        migrations.AddField(
            model_name='proc',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Person'),
        ),
    ]
