# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161018_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_id', models.CharField(default=uuid.uuid4, max_length=30, unique=True)),
                ('title', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('content', models.CharField(blank=True, max_length=255)),
                ('deadlines', models.CharField(blank=True, max_length=255)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.DocNode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='docs',
        ),
        migrations.AlterField(
            model_name='doc',
            name='long_id',
            field=models.CharField(default=uuid.uuid4, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='hat',
            name='long_id',
            field=models.CharField(default=uuid.uuid4, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='docnode',
            name='people',
            field=models.ManyToManyField(blank=True, to='core.Person'),
        ),
        migrations.AddField(
            model_name='doc',
            name='root_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DocNode'),
        ),
    ]
