# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161024_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='long_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='docnode',
            name='long_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='hat',
            name='long_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
