# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161024_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='icon',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='icon',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='proc',
            name='icon',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
