# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161024_0758'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocNode',
            new_name='DocsNode',
        ),
    ]
