# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161024_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proc',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons'),
        ),
    ]
