# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20161025_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='icon',
            field=models.FileField(blank=True, upload_to='doc_icons'),
        ),
        migrations.AlterField(
            model_name='person',
            name='icon',
            field=models.FileField(blank=True, upload_to='person_icons'),
        ),
    ]
